# Generated by Django 5.1.3 on 2024-12-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
