# Generated by Django 5.1.3 on 2024-12-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0005_alter_issue_date_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('credit', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('register', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('registerdate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.png', upload_to='profile_pics')),
            ],
        ),
    ]
