# Generated by Django 5.1.3 on 2025-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0006_cousemodule_registration1_student1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student1',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
